version: '3.4'

services:
  skoruba.identityserver4.admin:
    image: ${DOCKER_REGISTRY-}skoruba-identityserver4-admin
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.Admin/Dockerfile
    container_name: skoruba-identityserver4-admin
    environment:
      - "ConnectionStrings__ConfigurationDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__DataProtectionDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=https://127.0.0.1.xip.io:9043"
      - "AdminConfiguration__IdentityAdminRedirectUri=https://127.0.0.1.xip.io:9043/signin-oidc"
      - "AdminConfiguration__IdentityServerBaseUrl=https://127.0.0.1.xip.io"
      - "AdminConfiguration__RequireHttpsMetadata=true"
      - "IdentityServerData__Clients__0__ClientUri=https://127.0.0.1.xip.io:9043"
      - "IdentityServerData__Clients__0__RedirectUris__0=https://127.0.0.1.xip.io:9043/signin-oidc"
      - "IdentityServerData__Clients__0__FrontChannelLogoutUri=https://127.0.0.1.xip.io:9043/signin-oidc"
      - "IdentityServerData__Clients__0__PostLogoutRedirectUris__0=https://127.0.0.1.xip.io:9043/signout-callback-oidc"
      - "IdentityServerData__Clients__0__AllowedCorsOrigins__0=https://127.0.0.1.xip.io:9043"
      - "IdentityServerData__Clients__1__RedirectUris__0=https://127.0.0.1.xip.io:5043/swagger/oauth2-redirect.html"
      - "Serilog__WriteTo__1__Args__connectionString=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
    command: dotnet Skoruba.IdentityServer4.Admin.dll /seed
    depends_on:
      - skoruba.identityserver4.sts.identity
    volumes:
      - "./shared/serilog.json:/app/serilog.json"
      - "./shared/identitydata.json:/app/identitydata.json"
      - "./shared/identityserverdata.json:/app/identityserverdata.json"

  skoruba.identityserver4.admin.api:
    image: ${DOCKER_REGISTRY-}skoruba-identityserver4-admin-api
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.Admin.Api/Dockerfile
    environment:
      - "AdminApiConfiguration__RequireHttpsMetadata=true"
      - "AdminApiConfiguration__ApiBaseUrl=https://127.0.0.1.xip.io:5043"
      - "AdminApiConfiguration__IdentityServerBaseUrl=https://127.0.0.1.xip.io"
      - "ConnectionStrings__ConfigurationDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminLogDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__AdminAuditLogDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__DataProtectionDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
    container_name: skoruba-identityserver4-admin-api
    volumes:
      - "./shared/serilog.json:/app/serilog.json"

  skoruba.identityserver4.sts.identity:
    image: ${DOCKER_REGISTRY-}skoruba-identityserver4-sts-identity
    build:
      context: .
      dockerfile: src/Skoruba.IdentityServer4.STS.Identity/Dockerfile
    container_name: skoruba-identityserver4-sts-identity
    environment:
      - "ConnectionStrings__ConfigurationDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__PersistedGrantDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__IdentityDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "ConnectionStrings__DataProtectionDbConnection=Server=host.docker.internal;Database=IdentityServer4Admin;User Id=sa;Password=${DB_PASSWORD:-Password@123};MultipleActiveResultSets=true"
      - "AdminConfiguration__IdentityAdminBaseUrl=https://127.0.0.1.xip.io:9043"
    volumes:
      - "./shared/serilog.json:/app/serilog.json"
    networks:
      default:
        aliases:
          - 127.0.0.1.xip.io
#  db:
#    image: "mcr.microsoft.com/mssql/server"
#    ports:
#      - 1433:1433
#    container_name: skoruba-identityserver4-db
#    environment:
#      SA_PASSWORD: "${DB_PASSWORD:-Password@123}"
#      ACCEPT_EULA: "Y"
#    volumes:
#      - D:\docker\sqlServer\mssqldb\:/var/opt/mssql:z

volumes:
  dbdata:
    driver: local

networks:
  default:
    driver: bridge