version: '3.4'

services:
  skoruba.identityserver4.admin:
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  "bin/Debug/netcoreapp3.1/Skoruba.IdentityServer4.Admin.dll" /seed'

  skoruba.identityserver4.admin.api:
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  skoruba.identityserver4.sts.identity:
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
